# Generated by Django 2.2 on 2019-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_death_report', '0001_initial'),
        ('cancer_prn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdeath',
            name='cause',
        ),
        migrations.AddField(
            model_name='subjectdeath',
            name='cause',
            field=models.ManyToManyField(to='edc_death_report.Cause', verbose_name='What is the primary source of cause of death information? (if multiple source of information, list one with the smallest number closest to the top of the list) '),
        ),
    ]
