# Generated by Django 2.2 on 2019-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_death_report', '0001_initial'),
        ('cancer_prn', '0002_auto_20190425_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdeath',
            name='cause_category',
        ),
        migrations.AddField(
            model_name='subjectdeath',
            name='cause_category',
            field=models.ManyToManyField(to='edc_death_report.CauseCategory', verbose_name='Based on the above description, what category best defines the major cause of death? '),
        ),
        migrations.RemoveField(
            model_name='subjectdeath',
            name='diagnosis_code',
        ),
        migrations.AddField(
            model_name='subjectdeath',
            name='diagnosis_code',
            field=models.ManyToManyField(help_text='Use diagnosis code from Diagnosis Reference Listing', max_length=25, to='edc_death_report.DiagnosisCode', verbose_name='Please code the cause of death as one of the following:'),
        ),
        migrations.RemoveField(
            model_name='subjectdeath',
            name='medical_responsibility',
        ),
        migrations.AddField(
            model_name='subjectdeath',
            name='medical_responsibility',
            field=models.ManyToManyField(to='edc_death_report.MedicalResponsibility', verbose_name='Who was responsible for primary medical care of the participant during the month prior to death?'),
        ),
        migrations.RemoveField(
            model_name='subjectdeath',
            name='reason_hospitalized',
        ),
        migrations.AddField(
            model_name='subjectdeath',
            name='reason_hospitalized',
            field=models.ManyToManyField(blank=True, null=True, to='edc_death_report.ReasonHospitalized', verbose_name='if yes, hospitalized, what was the primary reason for hospitalisation? '),
        ),
    ]
